<?php $stylesheetDir = IMAGESERVE_DIR . "/assets/css/style.css"; ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php echo APP_NAME . " - Error"; ?></title>
        <link rel="stylesheet" href="<?php echo $stylesheetDir; ?>">
    </head>

    <body>
        <h1>Uh Oh!</h1>
		<h2>Looks like this page doesn't exist.</h2>
		<p>- Alan D'souza</p>
    </body>
</html>
